spring.datasource.url=jdbc:mysql://kafka-32f68d16-dantehemant-4e24.d.aivencloud.com:10344/kafka-32f68d16
spring.datasource.username=avnadmin
spring.datasource.password=AVNS_JZlmy_iiLMJaVyCWbjc

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

ddl-auto=update
show-sql=true

server.port=8080